name: GitHub Actions Demo
on: [push]
jobs:
  lint-markdown:
    name: lint file
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/igorshubovych/markdownlint-cli:latest
      volumes: $PWD:/workdir
      workdir: /workdir
    steps:
    - run: |
        pwd
