name:  gh-actions

on: [push]

jobs:

  lint-markdown:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: debug output
      uses: docker://ghcr.io/igorshubovych/markdownlint-cli:latest
      with:
        args: ./notes/t*.md --disable MD013 MD025 MD010 MD012
