name: GitHub Actions Demo
on: [push]

jobs:
#  node-docker:
#    runs-on: ubuntu-latest
#    container:
#      image: node:14.15.0-alpine3.12
#    steps:
#    - name: Log the node version
#      run: |
#        node -v
#        cat /etc/os-release  
  lint-markdown:
    runs-on: ubuntu-latest
    #container:
    #  image: ghcr.io/igorshubovych/markdownlint-cli:latest
    #  options: -v ${{github.workspace}}:/workdir:rw --workdir /workdir
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: debug output
      uses: docker://ghcr.io/igorshubovych/markdownlint-cli:latest
      with:
        entrypoint: ""
        #args: -v ${{github.workspace}}:/workdir:rw --workdir /workdir
        args: ls -lah
